-- Create RAB table
create table if not exists public.rab (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  category text not null,
  budget numeric not null default 0,
  realization numeric not null default 0,
  percent numeric not null default 0,
  status text not null default 'Belum Dimulai',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.rab enable row level security;

-- Allow public read access (adjust as needed for your app)
create policy "Public read access" on public.rab for select using (true);

-- Allow public insert access (adjust as needed for your app)
create policy "Public insert access" on public.rab for insert with check (true);

-- Allow public update access (adjust as needed for your app)
create policy "Public update access" on public.rab for update using (true);

-- Allow public delete access (adjust as needed for your app)
create policy "Public delete access" on public.rab for delete using (true);

-- Create updated_at trigger
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

create trigger set_updated_at
  before update on public.rab
  for each row execute procedure public.handle_updated_at();
